
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '100'
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf:
    cache: 'false'
  thymeleaf3:
    decoupled-logic: 'true'
  devtools:
    restart:
      quiet-period: 800ms
  config:
    activate:
      on-profile: alpha
  datasource:
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://b2fe33867c5eb6:3bf314b4@us-cdbr-east-04.cleardb.com/heroku_74931efe97faf8e?reconnect=true
  h2:
    console:
      enabled: 'false'
  sql:
    init:
      mode: never
debug: 'false'
logging:
  level:
    com:
      sping: debug
    org:
      springframework:
        web:
          servlet: debug
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
server:
  error:
    whitelabel:
      enabled: 'false'
